server:
  port: 8100
  tomcat:
    threads:
      max: 1024

spring:
  application:
    name: woniu-generator
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:log4jdbc:mysql://localhost:3306/pm-admin?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=UTC
    username: root
    password: pang!(&*1103

mybatis:
  type-aliases-package: com.woniu.**.entity
  mapper-locations: classpath*:mapper/**/*Mapper.xml

woniu:
  code-generate:
    output-path: /data/buffer
